#ifndef CONST_H
#define CONST_H

#define GAME_NAME "Space"

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define PLAYER_WIDTH 50.f
#define PLAYER_HEIGHT 20.f
#define PLAYER_X_CENTER (PLAYER_WIDTH / 2.f)
#define PLAYER_Y_CENTER (PLAYER_HEIGHT / 2.f)

#define UPPER_LIMIT -PLAYER_WIDTH
#define LOWER_LIMIT WINDOW_HEIGHT+PLAYER_WIDTH
#define LEFT_LIMIT -PLAYER_WIDTH
#define RIGHT_LIMIT WINDOW_WIDTH+PLAYER_WIDTH

#define MAX_SPEED 3.8
#define MAX_ROTATION_SPEED 1.3

#endif // !CONST_H
