#ifndef CONST_H
#define CONST_H

#define GAME_NAME "Space"

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define CHARACTER_WIDTH 60.f
#define CHARACTER_HEIGHT 30.f
#define CHARACTER_X_CENTER (CHARACTER_WIDTH / 2.f)
#define CHARACTER_Y_CENTER (CHARACTER_HEIGHT / 2.f)

#define BULLET_WIDTH 30.f
#define BULLET_HEIGHT 10.f
#define BULLET_X_CENTER (BULLET_WIDTH / 2.f)
#define BULLET_Y_CENTER (BULLET_HEIGHT / 2.f)
#define BULLET_SPEED 8.6
#define BULLET_LIFETIME 2.0

#define UPPER_LIMIT -CHARACTER_WIDTH
#define LOWER_LIMIT WINDOW_HEIGHT+CHARACTER_WIDTH
#define LEFT_LIMIT -CHARACTER_WIDTH
#define RIGHT_LIMIT WINDOW_WIDTH+CHARACTER_WIDTH

#define MAX_SPEED 3.6
#define MAX_ROTATION_SPEED 1.8

#endif // !CONST_HPP
